project: 
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: 1
    comments:
      hypothesis: true
  docx: default
  pdf:
    toc: true
    toc-depth: 3
    toc-expand: 1
    comments:
      hypothesis: true